name: esgf-build
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2018.11.29=ha4d7672_0
  - certifi=2018.11.29=py27_1000
  - click=7.0=py_0
  - ecdsa=0.13=py_0
  - gitdb2=2.0.5=py_0
  - gitpython=2.1.11=py_0
  - libcxx=7.0.0=h2d50403_2
  - libffi=3.2.1=h0a44026_1005
  - llvm-meta=7.0.0=0
  - ncurses=6.1=h0a44026_1002
  - openssl=1.1.1a=h1de35cc_1000
  - paramiko=1.18.2=py27_0
  - pip=19.0.1=py27_0
  - plumbum=1.6.7=py_0
  - pycrypto=2.6.1=py27h1de35cc_1002
  - readline=7.0=hcfe32e1_1001
  - semver=2.8.1=py_1
  - setuptools=40.7.1=py27_0
  - smmap2=2.0.5=py_0
  - sphinx_rtd_theme=0.4.2=py_0
  - sqlite=3.26.0=h1765d9f_1000
  - tk=8.6.9=ha441bb4_1000
  - wheel=0.32.3=py27_0
  - zlib=1.2.11=h1de35cc_1004
  - python=2.7.15=h8f8e585_6
  - pip:
    - githubrelease
prefix: /Users/hill119/anaconda2/envs/esgf-build
